payload:
  - "PROCESS-NAME,svchost.exe"
  - "PROCESS-NAME,HYPHelper.exe"
  - "PROCESS-NAME,HYP.exe"
  - "PROCESS-NAME,UplayWebCore.exe"
  - "PROCESS-NAME,upc.exe"
  - "PROCESS-NAME,Thunder"
  - "PROCESS-NAME,EpicGamesLauncher.exe"
  - "PROCESS-NAME,TextInputHost.exe"
  - "PROCESS-NAME,WebTorrent"
  - "PROCESS-NAME,WebTorrent Helper"
  - "PROCESS-NAME,DownloadService"
  - "PROCESS-NAME,Weiyun"
  - "PROCESS-NAME,msedge.exe"
  - "PROCESS-NAME,SystemSettings.exe"
  - "PROCESS-NAME,python.exe"
  - "PROCESS-NAME,steam.exe"
  - "PROCESS-NAME,com.unionpay"
  - "PROCESS-NAME,KRInstallExternal.exe"
  - "PROCESS-NAME,EAappInstaller.exe"
  - "PROCESS-NAME,EACefSubProcess.exe"
  - "PROCESS-NAME,EADesktop.exe"
  - "PROCESS-NAME,EABackgroundService.exe"
  - "PROCESS-NAME,com.ubisoft.uplay"
  - "PROCESS-NAME,Client-Win64-Shipping.exe"
  - "PROCESS-NAME,launcher.exe"
